### ISSUE TITLE
About open_api_spex dependency

### ISSUE THREAD

**Issue by dcdourado** [wingyplus/redoc_ui_plug#6]
Maybe this library could not have `:open_api_spex` as a dependency and leave the decision to the user to use it or not to generate the OAS.

**Comment by wingyplus** [comment]
I have a plan to add code example which’s require to have open_api_spex. 

I’m not sure about the effort to make it as an optional after this feature landed. So let keep this open for now. :)

BTW thank you for interesting in the library. 🙇‍♂️

**Comment by wingyplus** [comment]
Close by https://github.com/wingyplus/redoc_ui_plug/commit/4d2bc892fa6da5ce465d1c0b58a2d8f65888ab19

Released on v0.2.0
